; Written by ~/.config/mango/apply-theme.sh from the wallpaper's colour word
[wallpaper]
text               = ffffff
subtext            = b3b3b3
main               = 0a0a0a
main-elevated      = 141414
sidebar            = 0a0a0a
player             = 0a0a0a
card               = 1a1a1a
shadow             = 000000
selected-row       = ffffff
button             = ffffff
button-active      = ffffff
button-disabled    = 666666
tab-active         = 404040
notification       = ffffff
notification-error = ffffff
misc               = 404040
highlight          = 1a1a1a
highlight-elevated = 404040
